export const types = {
    LOAD_POST_START : "LOAD_POST_START",
    LOAD_POST_SUCCESS : "LOAD_POST_SUCCESS",
    LOAD_POST_FAIL: "LOAD_POST_FAIL",
    ADD_PRODUCT_START: "ADD_PRODUCT_START",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAIL: "ADD_PRODUCT_FAIL"
};
